name: azurequantum
channels:
  - quantum-engineering
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pytest
  - numpy
  - deprecated
  - msrest
  - azure-core
  - azure-identity
  - azure-storage-blob
  - azure-mgmt-core
  - pip:
    - azure-devtools
